### ISSUE TITLE
Fullflash 

### ISSUE THREAD

**Issue by bobrenja** [alsar/wr01-firmware#1]
Hello. You need a dump for this model of the receiver. Thank you.

**Comment by alsar** [comment]
Hello. I don't really understand your comment. Can you elaborate?

**Comment by bobrenja** [comment]
Looking for such a model of a FULL dump router on a 25q16 chip

**Comment by alsar** [comment]
Sorry, I don't have a full dump.

**Comment by DarthKeizer** [comment]
Any updates since v28K.RPT.20180614 ?

**Comment by alsar** [comment]
I don't really now. I'm not using this particular repeater anymore.
